"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['EasySync.py']
DATA_FILES = [('', ['icon'])]
OPTIONS = {
    'iconfile': 'icon/EasySync.icns'
}
#'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
